Mimic.copy(WaltUi.Calendars)
Mimic.copy(WaltUi.Enrichment.Endato)
Mimic.copy(WaltUi.Enrichment.Endato.Http)
Mimic.copy(WaltUi.Enrichment.Faraday)
Mimic.copy(WaltUi.Enrichment.Faraday.Http)
Mimic.copy(WaltUi.Enrichment.Trestle.Http)
Mimic.copy(WaltUi.Enrichment.OpenAi)
Mimic.copy(WaltUi.Google.Auth.Http)
Mimic.copy(WaltUi.Google.Calendars)
Mimic.copy(WaltUi.Google.Gmail)
Mimic.copy(WaltUi.Google.VertexAI.Client)
Mimic.copy(WaltUi.HumanLoop.Http)
Mimic.copy(WaltUi.Notifications.Fcm.Http)
Mimic.copy(WaltUi.Skyslope.Auth.Http)
Mimic.copy(WaltUi.ExternalAccountsAuthHelper)
Mimic.copy(WaltUi.Geocoding)

Mimic.copy(ExTypesense)
Mimic.copy(Stripe.Customer)
Mimic.copy(Hammer)

ExUnit.start(capture_log: true)
Ecto.Adapters.SQL.Sandbox.mode(Repo, :manual)
Ecto.Adapters.SQL.Sandbox.mode(HouseCanaryRepo, :manual)
Faker.start()
