defmodule WaltUi.HouseCanaryFactory do
  @moduledoc false

  use ExMachina.Ecto, repo: HouseCanaryRepo

  def property_factory do
    %WaltUi.HouseCanary.Property{
      hc_address_id: sequence(:hc_address_id, & &1),
      assessment_edition: "24",
      hc_value_estimate: 350_000,
      address_slug: "123-Main-St-Columbus-OH-43215",
      address: "123 Main St",
      unit: nil,
      city: "Columbus",
      state: "OH",
      zipcode: "43215",
      zipcode_plus4: "1234",
      latitude: 39.9612,
      longitude: -82.9988,
      county: "Franklin",
      address_street_number: "123",
      address_street_name: "Main",
      address_street_type: "St",
      owner_occupied_yn: "Y",
      owner_name: "SMITH JOHN",
      owner_vesting_type: "JT",
      owner_address: "123 Main St",
      owner_unit_type: nil,
      owner_unit_number: nil,
      owner_city: "Columbus",
      owner_state: "OH",
      owner_zip: "43215",
      owner_zip_plus4: "1234",
      year_built: 1985,
      living_area: 2200.0,
      bedrooms: 4,
      bathrooms_total: 3,
      lot_size: 8500.0,
      last_close_date: ~D[2018-06-15],
      last_close_price: 285_000,
      last_close_buyer1: "SMITH JOHN",
      last_close_buyer2: nil,
      last_close_seller1: "DOE JANE",
      last_close_seller2: nil,
      deed_date: ~D[2018-06-15],
      deed_price: "285000",
      deed_type: "WD",
      deed_transfer_yn: "Y",
      lien1_borrower1_name: "SMITH JOHN",
      lien1_borrower1_first_name: "JOHN",
      lien1_borrower1_last_name: "SMITH",
      lien1_borrower2_name: nil,
      lien1_borrower2_first_name: nil,
      lien1_borrower2_last_name: nil,
      lien1_lender_name: "FIRST NATIONAL BANK",
      lien1_lender_type: "BANK",
      lien1_loan_term: 360,
      lien1_loan_type: "CNV",
      lien2_borrower1_name: nil,
      lien2_borrower1_first_name: nil,
      lien2_borrower1_last_name: nil,
      lien2_borrower2_name: nil,
      lien2_borrower2_first_name: nil,
      lien2_borrower2_last_name: nil,
      lien2_lender_name: nil,
      lien2_lender_type: nil
    }
  end
end
