defmodule WaltUi.AccountTest do
  use WaltUi.CqrsCase

  import WaltUi.Factory

  alias WaltUi.Account

  setup do
    [user: insert(:user)]
  end

  describe "list_users/0" do
    test "returns list of all users" do
      users = Account.list_users()
      assert length(users) > 0
      assert Enum.all?(users, fn user -> match?(%Account.User{}, user) end)
    end
  end

  describe "get_user/1" do
    test "returns user by id", ctx do
      assert %Account.User{} = Account.get_user(ctx.user.id)
    end

    test "returns nil if id not found" do
      refute Account.get_user(UUID.uuid4())
    end
  end

  describe "get_user_by_email/1" do
    test "returns user by email" do
      %{id: user_id} = insert(:user, email: "test@test.com")
      assert {:ok, %{id: ^user_id}} = Account.get_user_by_email("test@test.com")
    end

    test "returns error tuple if email not found" do
      assert {:error, :not_found} = Account.get_user_by_email("foo@bar.baz")
    end
  end

  describe "create_user/1" do
    test "creates user" do
      assert {:ok, %Account.User{id: user_id}} = Account.create_user(%{email: "test@test.org"})
      # user has ID generated by database
      assert user_id
    end

    test "returns error changeset" do
      assert {:error, %Ecto.Changeset{valid?: false}} = Account.create_user(%{})
    end
  end

  describe "find_or_create_user_by_oauth_user/1" do
    test "returns existing user by email address", ctx do
      user_id = ctx.user.id

      assert {:ok, %Account.User{id: ^user_id}} =
               Account.find_or_create_user_by_oauth_user(%{email: ctx.user.email})
    end

    test "creates user from attrs if existing user not found" do
      assert {:ok, %Account.User{id: user_id}} =
               Account.find_or_create_user_by_oauth_user(%{email: "foo@bar.baz"})

      # user has ID generated by database
      assert user_id
    end

    test "returns error changeset if user cannot be created" do
      assert {:error, %Ecto.Changeset{valid?: false}} =
               Account.find_or_create_user_by_oauth_user(%{email: ""})
    end
  end

  describe "update_user/2" do
    test "updates user data", ctx do
      user_id = ctx.user.id
      refute ctx.user.first_name == "Razor"

      assert {:ok, %Account.User{id: ^user_id}} =
               Account.update_user(ctx.user, %{first_name: "Razor"})

      assert %Account.User{first_name: "Razor"} = Repo.reload(ctx.user)
    end

    test "returns error changeset if user cannot be updated", ctx do
      assert {:error, %Ecto.Changeset{valid?: false}} =
               Account.update_user(ctx.user, %{email: ""})
    end
  end

  describe "delete_user/1" do
    test "deletes user data", ctx do
      assert {:ok, _} = Account.delete_user(ctx.user)
      refute Repo.reload(ctx.user)
    end

    test "deletes user contacts via CQRS", ctx do
      contact_1 = await_contact(user_id: ctx.user.id)
      contact_2 = await_contact(user_id: ctx.user.id)

      assert {:ok, _} = Account.delete_user(ctx.user)

      refute Repo.reload(contact_1)
      refute Repo.reload(contact_2)
    end
  end
end
