import Config

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :walt_ui, WaltUiWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"
config :marketing, MarketingWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: WaltUi.Finch

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :jsonapi,
  host: "app.heywalt.ai",
  scheme: "https",
  port: 443,
  # remove_links: false,
  # json_library: Jason,
  # paginator: nil,
  namespace: "/api",
  field_transformation: :underscore,
  page: :page

config :walt_ui, :skyslope, redirect_uri: "https://app.heywalt.ai/auth/skyslope/callback"

# Security settings for production
config :walt_ui, :secure_cookies, true
config :marketing, :secure_cookies, true

config :appsignal, :config, active: true, env: :prod

config :walt_ui, WaltUi.Contacts.CreateContactsConsumer,
  batch_size: 10,
  producer_options: [
    goth: WaltUi.Goth,
    subscription: "projects/heywalt/subscriptions/create-contacts-consumer"
  ]

config :walt_ui, WaltUi.Contacts.UpsertContactsConsumer,
  producer_options: [
    goth: WaltUi.Goth,
    subscription: "projects/heywalt/subscriptions/upsert-contacts-consumer"
  ],
  batcher_options: [
    batch_size: 10
  ]

config :walt_ui, Oban,
  plugins: [
    Oban.Pro.Plugins.DynamicPruner,
    {Oban.Pro.Plugins.DynamicLifeline, rescue_interval: :timer.minutes(10)},
    {Oban.Plugins.Cron,
     timezone: "America/New_York",
     crontab: [
       # 0001 everyday
       {"1 0 * * *", WaltUi.Mailchimp.UpdateContactCountJob},
       {"1 0 * * *", WaltUi.Account.UpdateUserTierJob},
       # 0100 everyday
       # TODO re-enable
       # {"0 1 * * *", WaltUi.Enrichment.ReEnrichmentCronJob},
       # 0400 every Sunday
       {"0 4 * * 0", WaltUi.Enrichment.JitterJob},
       # 10am every Sunday
       {"0 4 * * 0", WaltUi.Search.JitterSearchJob},
       # 0100 everyday
       {"0 1 * * *", WaltUi.Calendars.SyncJob},
       # 2am everyday
       {"0 2 * * *", WaltUi.Email.SyncEmailJob},
       # 0300 everyday
       {"0 3 * * *", WaltUi.Tasks.ExpiredSystemTasksCronJob},
       # 0305 everyday
       {"5 3 * * *", WaltUi.Tasks.UpcomingDateTasksCronJob},
       # 0200 everyday - Geocoding cleanup for premium users
       {"0 2 * * *", WaltUi.Geocoding.GeocodingCronJob}
     ]}
  ]
